export const BRAND = {
  name: "CapitalAI",
  shortName: "Capital",
  wordmarkSuffix: "AI",
  legalEntity: "CapitalAI",
  tagline: "Professional Brokerage & Wealth Management",
  domain: "capitalai.online",
  url: "https://www.capitalai.online",
  supportEmail: "support@capitalai.online",
  complianceEmail: "compliance@capitalai.online",
  registrationNumber: "CA-2021-001",
  foundedYear: 2021,
  twitter: "@CapitalAI",
  colors: {
    midnight: "#050202",
    charcoal: "#141212",
    surface: "#1C1C1C",
    white: "#FFFFFF",
    offWhite: "#F4F3F3",
    signatureGold: "#FBBE5B",
    goldDeep: "#D18812",
    goldHover: "#ECAF4B",
    coolBlue: "#41A6FF",
    muted: "#908A8A",
    // Legacy aliases used in code
    navy: "#050202",
    slate: "#1C1C1C",
    gold: "#D18812",
    emerald: "#FBBE5B",
    emeraldSoft: "#FFC764",
    emeraldGlow: "#ECAF4B",
  },
} as const;
